
name: CI CD deployment

on:
  push: 
   branches: [main]
  workflow_dispatch:
    
 permissions:
  contents: write
  # id-token: write
  # pull-requests: write

jobs:

    build_and_deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build Projetc
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        id: deploy-to-azure-static-web-apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'build'
          api_location: 'api'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      # - uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      #     action: 'upload'
      #     app_location: '/'
      #     output_location: 'build'
      #     api_location: 'api'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      
    

       
      

  
 
  
             